### ISSUE TITLE
Take a look at https://github.com/mithro/ixo-usb-jtag

### ISSUE THREAD

**Issue by mithro** [dpavlin/fx2fw-sdcc#1]
Hi,

I took a copy of the ixo-usb-jtag code, which is based on the fx2fw-sdcc code and reapplied your fixes for the latest sdcc to it. The end result ended up at https://github.com/mithro/ixo-usb-jtag with a more complete history then your version did and a bunch of other fixes. I was after the hw_nexys.c version of the firmware which your version doesn't include.

You may want to replace this repositories content with the content from mine.

Hope it helps!

Tim 'mithro' Ansell

**Comment by dpavlin** [comment]
Thanks, I replaced my code with your version and added pointer to your version which is indeed better than mine. Thanks for your work.

**Comment by mithro** [comment]
If you delete this repository and refork it then github will put the "forked from" bit in the title. I've been chatting with Hauke D to try and get work on the project restarted.

**Comment by dpavlin** [comment]
Good point. I'll do that.
